name: Auto Update Job Data Twice Daily

on:
  schedule:
    - cron: '30 0 * * *'  # Runs at 6:00 AM IST (12:30 AM UTC)
    - cron: '30 12 * * *' # Runs at 6:00 PM IST (12:30 PM UTC)
  workflow_dispatch:

jobs:
  update-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install openai

      - name: Run job summarizer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python summarize_jobs.py

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add jobs.json
          git commit -m "🤖 Auto-update jobs.json" || echo "No changes to commit"
          git push
